name: Setup Environment

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      php-version: ${{ steps.get-php.outputs.php-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP & Extensions
        uses: shivammathur/setup-php@v2
        id: get-php
        with:
          php-version: "8.4"
          extensions: mbstring, bcmath, ctype, fileinfo, json, openssl, pdo, pdo_mysql, tokenizer, xml, curl
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.18.0

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install frontend dependencies
        run: pnpm install

      - name: Compile assets
        run: pnpm run build

      - uses: actions/upload-artifact@v4
        with:
          name: built-assets
          path: |
            vendor
            public/build
